### ISSUE TITLE
Some words are not pronounced

### ISSUE THREAD

**Issue by mathigatti** [740291272/Sinsy-NG#3]
Hi, I am trying to choose the language but it seems to always generate the audio in english.

Is this the way to use the "-w" flag?
```
LD_LIBRARY_PATH=/usr/lib ./sinsyNG -w 'es-419' -o o.wav c.xml
```
Spanish specification es-491 works fine with espeak-ng, running something like this generates the desired output.
```
/usr/bin/espeak-ng -ves-419 "hola como te va"
```

**Comment by mathigatti** [comment]
It's working now with the -m flag :)

```
LD_LIBRARY_PATH=/usr/lib ./sinsyNG -m es -o o.wav c.xml
```

**Comment by mathigatti** [comment]
It seems to have problems with some words or phonemes, I generated a xml with the words "renta" and "ando" and it can't say them.

**Comment by mathigatti** [comment]
[This](https://drive.google.com/file/d/1pRfMMgJ5m5cejVfsHSVOJaVF1RU3frKt/view?usp=sharing) is the xml I am using. It should generate the voice saying something like "renta como ando va a vos amigo mio", but "renta" and "ando" are not pronounced. I tested it with "-m es" flag (spanish version) and without it (english version), none of them generates an audio where those words are pronounced.

espeakNG pronounce those correctly.

**Comment by YuzukiTsuru** [comment]
I'm sorry to keep you waiting. I've been busy lately. I don't have time for development. You can try changing the phoneme or the connector: ecantorix.:）

**Comment by mathigatti** [comment]
At [ecantorix.c](https://github.com/740291272/libespeak-NG/blob/master/src/libespeak-ng/ecantorix.c) changing `if(note->pitch!=255 && note->syllables==1)` for `if(note->pitch!=255)` and `if(note->syllables==1) tn_fnds_find_pulse_locations(note,0);` for `tn_fnds_find_pulse_locations(note,0);` seems to fix the problem.

**Comment by YuzukiTsuru** [comment]
You can open a pull request to merge your codes,and thanks for what you have done ^v^
