### ISSUE TITLE
is gloomyghost.com down?

### ISSUE THREAD

**Issue by mathigatti** [740291272/Sinsy-NG#4]

**Comment by YuzukiTsuru** [comment]
I rename my account and the cname is error,when i fix it,plz changed the domain name to github.gloomyghost.com, please use the new domain name to access

**Comment by YuzukiTsuru** [comment]
fixed

My main domain is being reviewed by China's filing office, so that I can legally operate the website in China.

**Comment by mathigatti** [comment]
Thanks!
